name: .NET publish release to NuGet
on:
  workflow_call:
    inputs:
      tests_to_run:
        required: false
        type: string
    secrets:
      NUGET_API_KEY:
        required: true

env:
  VERSION: ${{github.ref_name}}

jobs:
  publish-to-nuget:
    name: Build, test and publish to NuGet.org
    runs-on: ubuntu-22.04
    steps:
      - run: echo "ASSEMBLY_VERSION=$(echo $VERSION | sed -e 's/-.*//')" >> $GITHUB_ENV
      - uses: actions/checkout@v3
      - uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.401
      - run: dotnet build -c Release /p:Version=${{env.VERSION}} /p:AssemblyVersion=${{env.ASSEMBLY_VERSION}}
      - run: dotnet test -c Release ${{inputs.tests_to_run}}
      - run: dotnet pack -c Release -o nugetPackage -p:PackageVersion=${{env.VERSION}}
      - run: dotnet nuget push nugetPackage/*.nupkg -k ${{secrets.NUGET_API_KEY}} -s https://api.nuget.org/v3/index.json
