name: .NET build and test (Release)
on:
  workflow_call:
    inputs:
      tests_to_run:
        required: false
        type: string

jobs:
  build-and-test:
    name: Build and test
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.401
      - run: dotnet build -c Release
      - run: dotnet test -c Release ${{ inputs.tests_to_run }}
